on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.6

      - name: Install dependencies
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk

      - name: Install gdrive
        run: |
          wget -O /usr/local/bin/gdrive https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64
          chmod +x /usr/local/bin/gdrive
        env:
          LATEST_VERSION: v2.1.1

      - name: Upload to Google Drive
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_ACCOUNT }} > /tmp/credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/credentials.json"
          
          # Create the folder on Google Drive (replace 'MyApp' with your folder name)
          FOLDER_ID=$(gdrive mkdir "MyApp" | awk '/Directory/ {print $2}')

          # Upload files to the folder
          gdrive upload --file ./build/app/outputs/flutter-apk/app-release.apk --name "MyApp-Release.apk" --parent $FOLDER_ID --mime application/vnd.android.package-archive
