on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.6

      - name: Install dependencies
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk

      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Upload to Google Drive
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > /tmp/rclone.conf
          rclone --config=/tmp/rclone.conf copy ./build/app/outputs/flutter-apk/app-release.apk remote:https://drive.google.com/drive/u/0/folders/1ILi3ukF3q_XneBpTpCrQ1uhXAW57lI7r
